### ISSUE TITLE
Error - Property metadata is not allowed

### ISSUE THREAD

**Issue by rcblackwell** [hassio-addons/addon-vscode-remote#106]
# Problem/Motivation

Two scenes in my SCENES.YAML file are showing an error - "Property Metadata is not allowed". The scenes showing the error were created using the UI Editor. The YAML checker does not report an error in this file.

## Expected behavior

No errors errors identified

## Actual behavior

```
  metadata:  **Property metadata is not allowed**
    switch.master:
      entity_only: false
    switch.master_hallway_led:
      entity_only: false
- id: '1655321543393'
  name: GHS - Master Hallway On
  entities:
    switch.master:
      icon: mdi:light-switch
      friendly_name: Master Hallway
      state: 'on'
    switch.master_hallway_led:
      icon: mdi:led-on
      friendly_name: Master Hallway LED
      state: 'on'
  icon: mdi:ceiling-light
  metadata:  **Property metadata is not allowed**
    switch.master:
      entity_only: false
    switch.master_hallway_led:
      entity_only: false
```

VSCode Details;

code-server: v4.4.0
Code: 1.66.2
Commit: Unknown
Date: 2022-05-06T15:02:09.829Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
